version: '3.3'
volumes:
  media:
  static:
  pg_data:
services:
  postgres:
      container_name: foodgram-db
      image: postgres:15.2-alpine
      env_file: ../.env
      volumes:
        - pg_data:/var/lib/postgresql/data
      ports:
        - '5432:5432'
  frontend:
    container_name: foodgram-front
    build: ../frontend
    volumes:
      - ../frontend/:/app/result_build/
  nginx:
    container_name: foodgram-proxy
    image: nginx:1.25.4-alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../docs/:/usr/share/nginx/html/api/docs/
      - static:/usr/share/nginx/html/
      - media:/usr/share/nginx/html/media/
  backend:
    container_name: foodgram-back
    build: ../backend
    env_file: ../.env
    depends_on:
      - postgres
    volumes:
      - static:/collected_static/
      - media:/app/media/
